DROP DATABASE IF EXISTS Oscars;

CREATE DATABASE Oscars;

USE Oscars;
 
CREATE TABLE Ceremony(
Ceremony_ID INT PRIMARY KEY,
Year INT NOT NULL);

CREATE TABLE Country(
Country_ID INT PRIMARY KEY,
Country_name VARCHAR(50) NOT NULL,
Country_code VARCHAR(10) NOT NULL);

CREATE TABLE Person(
Person_ID INT AUTO_INCREMENT PRIMARY KEY,
Person_name VARCHAR(255) NOT NULL,
Gender CHAR(1) NOT NULL,
Country_ID INT,
FOREIGN KEY (Country_ID) REFERENCES Country(Country_ID) ON DELETE CASCADE ON UPDATE CASCADE);
  
CREATE TABLE Film(
Film_ID INT AUTO_INCREMENT PRIMARY KEY,
Film_title VARCHAR(50) NOT NULL,
genre VARCHAR(50) NOT NULL,
language VARCHAR(50),
Ceremony_ID INT,
FOREIGN KEY (Ceremony_ID) REFERENCES Ceremony(Ceremony_ID) ON DELETE CASCADE ON UPDATE CASCADE);


CREATE TABLE Award(
Award_ID INT PRIMARY KEY,
Award_name VARCHAR(50) NOT NULL,
Ceremony_ID INT NOT NULL,
Film_ID INT,
Person_ID INT,
FOREIGN KEY (Ceremony_ID) REFERENCES Ceremony(Ceremony_ID) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (Film_ID) REFERENCES Film(Film_ID) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (Person_ID) REFERENCES Person(Person_ID) ON DELETE CASCADE ON UPDATE CASCADE);


CREATE TABLE Nominee(
Nominee_ID INT AUTO_INCREMENT PRIMARY KEY,
Award_ID INT NOT NULL,
Film_ID INT NOT NULL,
Person_ID INT NOT NULL,
Is_Winner Boolean,
Category VARCHAR(50),
FOREIGN KEY (Film_ID) REFERENCES Film(Film_ID) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (Person_ID) REFERENCES Person(Person_ID) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (Award_ID) REFERENCES Award(Award_ID) ON DELETE CASCADE ON UPDATE CASCADE);


CREATE TABLE Act(
Person_ID INT,
Film_ID INT,
Role VARCHAR(50) NOT NULL,
PRIMARY KEY(Person_ID,Film_ID),
FOREIGN KEY (Film_ID) REFERENCES Film(Film_ID) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (Person_ID) REFERENCES Person(Person_ID) ON DELETE CASCADE ON UPDATE CASCADE);

